imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: sonata/sonata_cache.yml }
    - { resource: sonata/sonata_block.yml }
    - { resource: sonata/sonata_admin.yml }
    - { resource: sonata/sonata_media.yml }
    - { resource: sonata/sonata_classification.yml }
#    - { resource: sonata/sonata_formatter.yml }
    - { resource: sonata/sonata_user.yml }
    - { resource: fos_user.yml }
#    - { resource: intranet.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form_themes:
        - 'VichUploaderBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
#    java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        yui_css:
             jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
             apply_to: \.css$
        yui_js:
             jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
             apply_to: \.js$

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   %database_driver%
                dbname:   %database_name%
                user:     %database_user%
                host:     %database_host%
                password: %database_password%


        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        default_entity_manager: default
#        auto_mapping: true

        entity_managers:
            default:
                #metadata_cache_driver: apc
                #query_cache_driver: apc
                #result_cache_driver: apc
                mappings:
                    UPRedesIntranetBundle: ~
                    SonataMediaBundle: ~
                    ApplicationSonataMediaBundle: ~
                    SonataClassificationBundle: ~
                    ApplicationSonataClassificationBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

# stof_doctrine_extensions:
#     default_locale: es
#     translation_fallback: true
#     orm:
#         default:
#             sluggable: true

vich_uploader:
    db_driver: orm
    mappings:
        header_image_desktop:
            uri_prefix: /images/headers
            upload_destination: %kernel.root_dir%/../web/images/headers
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        header_image_mobile:
            uri_prefix: /images/headers/mobile
            upload_destination: %kernel.root_dir%/../web/images/headers/mobile
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        link_image:
            uri_prefix: /images/links/
            upload_destination: %kernel.root_dir%/../web/images/links
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

jms_serializer:
    handlers:
#        datetime:
#            default_format: "c" # ISO8601
#            default_timezone: "UTC" # defaults to whatever timezone set in php.ini or via date_default_timezone_set

    property_naming:
        separator:  _
        lower_case: true

    metadata:
        cache: file
        debug: "%kernel.debug%"
        file_cache:
            dir: "%kernel.cache_dir%/serializer"

services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    upredes.intranet.admin.category:
        class: UPRedes\IntranetBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Intranet, label: Category }
        arguments: [null, UPRedes\IntranetBundle\Entity\Category, UPRedesIntranetBundle:CategoryAdmin]

    upredes.intranet.admin.link:
        class: UPRedes\IntranetBundle\Admin\LinkAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Intranet, label: Link }
        arguments: [null, UPRedes\IntranetBundle\Entity\Link, UPRedesIntranetBundle:LinkAdmin]

    upredes.intranet.admin.header:
        class: UPRedes\IntranetBundle\Admin\HeaderAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Intranet, label: Header }
        arguments: [null, UPRedes\IntranetBundle\Entity\Header, UPRedesIntranetBundle:HeaderAdmin]

rss_client:
    channels:
        channel_upr:
            - 'http://noticias.upr.edu.cu/?feed=rss2'
            - 'http://elnodo.upr.edu.cu/?feed=rss2'


doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations