imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: sonata/sonata_cache.yml }
    - { resource: sonata/sonata_block.yml }
    - { resource: sonata/sonata_admin.yml }
    - { resource: sonata/sonata_media.yml }
#    - { resource: sonata/sonata_formatter.yml }
#    - { resource: sonata/sonata_seo.yml }
    - { resource: sonata/sonata_user.yml }
#    - { resource: sonata/sonata_page.yml }
#    - { resource: sonata/sonata_notification.yml }
    - { resource: fos_user.yml }
#    - { resource: intranet.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
#    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   %database_driver%
                dbname:   %database_name%
                user:     %database_user%
                host:     %database_host%
                password: %database_password%


        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        default_entity_manager: default
#        auto_mapping: true

        entity_managers:
            default:
                #metadata_cache_driver: apc
                #query_cache_driver: apc
                #result_cache_driver: apc
                mappings:
                    UPRedesIntranetBundle: ~
                    ApplicationSonataMediaBundle: ~
#                    gedmo_translatable:
#                        type: annotation
#                        prefix: Gedmo\Translatable\Entity
#                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
#                        alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
#                        is_bundle: false
#                    gedmo_translator:
#                        type: annotation
#                        prefix: Gedmo\Translator\Entity
#                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
#                        alias: GedmoTranslator # this one is optional and will default to the name set for the mapping
#                        is_bundle: false
#                    gedmo_loggable:
#                        type: annotation
#                        prefix: Gedmo\Loggable\Entity
#                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
#                        alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
#                        is_bundle: false
#                    gedmo_tree:
#                        type: annotation
#                        prefix: Gedmo\Tree\Entity
#                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
#                        alias: GedmoTree # this one is optional and will default to the name set for the mapping
#                        is_bundle: false

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

#stof_doctrine_extensions:
#    default_locale: es
#    translation_fallback: true
#    orm:
#        default:
#            translatable: true

services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    upredes.intranet.admin.category:
        class: UPRedes\IntranetBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Intranet, label: Category }
        arguments: [null, UPRedes\IntranetBundle\Entity\Category, UPRedesIntranetBundle:CategoryAdmin]

    upredes.intranet.admin.link:
        class: UPRedes\IntranetBundle\Admin\LinkAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Intranet, label: Link }
        arguments: [null, UPRedes\IntranetBundle\Entity\Link, UPRedesIntranetBundle:LinkAdmin]

rss_client:
   channels:

      channel_upr:
         - 'http://noticias.upr.edu.cu/index.php?format=feed&type=rss'

