<?php

namespace UPRedes\IntranetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function findAllOrderedByWeight()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM UPRedesIntranetBundle:Category c ORDER BY c.weight DESC'
            )
            ->getResult();
    }
}
