<?php

namespace UPRedes\IntranetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkRepository extends EntityRepository
{
    public function findByCategoryId($id)
    {
        $query = $this->getEntityManager()->createQuery('
            SELECT l, c FROM UPRedesIntranetBundle:Link l
                JOIN l.category c
                WHERE c.id = :id
                ORDER BY l.weight DESC'
        )->setParameter('id', $id);

        $query->useResultCache(true);

        return $query->getResult();
    }
}
